# Generated by Django 2.1.5 on 2019-04-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190331_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_track',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
